const DEFAULT_AI_CHAT_EXPERIMENT_FLAG_KEY = "ai-chat-experiment";

export const AI_CHAT_EXPERIMENT_FLAG_KEY =
  process.env.NEXT_PUBLIC_DATABUDDY_AI_CHAT_FLAG_KEY ??
  process.env.DATABUDDY_AI_CHAT_FLAG_KEY ??
  DEFAULT_AI_CHAT_EXPERIMENT_FLAG_KEY;

export const DATABUDDY_DASHBOARD_CLIENT_ID =
  process.env.NEXT_PUBLIC_DATABUDDY_DASHBOARD_WEBSITE_ID ??
  process.env.DATABUDDY_DASHBOARD_WEBSITE_ID ??
  "";
