export const CHAT_ABORT_FLAG_TTL_SECONDS = 300;
export const CHAT_ABORT_POLL_INTERVAL_MS = 500;
export const CHAT_TITLE_MAX_LENGTH = 80;
export const CHAT_DELETION_TOMBSTONE_TTL_SECONDS = 60 * 60 * 24 * 7;
